### ISSUE TITLE
Support grouping of methods via Tags

### ISSUE THREAD

**Issue by ColinEberhardt** [ColinEberhardt/openapi-forge#18]
People often use tags as a way to group API methods, e.g. 'Orders', 'Accounts', it would be a nice feature to generate these grouped methods as separate files / classes

**Comment by jhowlett-scottlogic** [comment]
Multiple tags can be assigned to one endpoint. I am therefore thinking of using the first tag in the array to decide its grouping and will add a comment of all tags above the endpoint method to prevent loss of information during forging. Otherwise duplicate endpoint methods will be generated. My solution should help prevent an issue like this: https://github.com/OpenAPITools/openapi-generator/issues/312.

Also at the top of all tag grouped files the description associated with the tag will be a comment at the top of the file
